strategy:
  pagination:
    page-size: 10
  pricing:
    context:
      risk-free-rate: 0.05
      volatility: 0.3

resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: 1
        limit-refresh-period: 1s
        timeout-duration: 2s
    instances:
      alphaVantageLimit:
        base-config: default
      finnHubLimit:
        limitForPeriod: 30
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms
integration:
  alphavantage:
    api:
      key: ${ALPHAVANTAGE_API_KEY}
  finnhub:
    api:
      token: ${FINNHUB_API_TOKEN}


spring:
  data:
    mongodb:
      uri: ${MONGO_URI}

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000