### 1. Retrieve and set JWT token
POST http://localhost:8080/api/auth/login
Content-Type: application/json

### 1. Retrieve and set JWT token
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "Wuaschii",
  "password": "WebDev422##%%"
}

> {%
    client.global.set("jwtToken", response.body.token);
    client.log("New jwt token: " + client.global.get("jwtToken"));
%}
### 2. Valid company search request
GET http://localhost:8080/companies/microsoft
Authorization: Bearer {{jwtToken}}

### 3. Testing if the charts are being correctly drawn
POST http://localhost:8080/preview
Content-Type: application/json

{
  "Strategy Type": "Vertical Spread",
  "quantity": 1,
  "position": "BUY",
  "strategyName": "MSFT Test Vertical",
  "optionType": "CALL",
  "spreadSize": 10.0,
  "expiryDate": "2026-08-20",
  "selectedCompany": {
    "ticker": "MSFT",
    "name": "Microsoft Corporation",
    "region": "United States"
  }
}
